apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ./vendor/katalog/monitoring/prometheus-operator
  - ./vendor/katalog/monitoring/prometheus-operated
  - ./vendor/katalog/monitoring/grafana
#  - ./vendor/katalog/kong/kong

resources:
  - ./services.yml