apiVersion: v1
kind: Service
metadata:
  name: grafana-exposed
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: http
      nodePort: 30001
  selector:
    app: grafana
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
  name: prometheus-k8s-exposed
  namespace: monitoring
spec:
  ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: web
      nodePort: 30002
  selector:
    app: prometheus
    prometheus: k8s
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: NodePort