apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: prometheus
  namespace: petstore
  labels:
    global: "true"
  annotations:
    kubernetes.io/ingress.class: 'kong'
plugin: prometheus