apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: methods-customization
  namespace: petstore
  annotations:
    kubernetes.io/ingress.class: 'kong'
route:
  methods:
    - POST