apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: basic-auth
  namespace: petstore
  annotations:
    kubernetes.io/ingress.class: 'kong'
config:
  hide_credentials: true
plugin: basic-auth