apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: user2
  namespace: petstore
  annotations:
    kubernetes.io/ingress.class: 'kong'
username: user
credentials:
  - user2
---
apiVersion: v1
kind: Secret
metadata:
  name: user2
  namespace: petstore
stringData:
  kongCredType: basic-auth
  password: "654321"
  username: "user2"